:label: add new endpoint specs
carbonaut-cloud/carbonaut pull request #6
Opened 2022-10-26 19:20 UTC by bcesur

2022-10-26 21:47 UTC, leonardpahlke requested changes
I think we can connect both versions a bit more and find ways to make the model more generic and easy to use. Probably we need to rearrange some things in the first version (which I created a few days ago) as well to make that work. I think we can keep an eye on emissions now (maybe rephrase some things that are called carbon to emissions) and later we can also add endpoints for energy data and so on :) Thanks @bcesur

2022-10-26 21:47 UTC, leonardpahlke commented on api/v1/api.proto
> +  string region = 5;
reuse `Location`
```suggestion
Location location = 5;
```

2022-10-26 21:47 UTC, leonardpahlke commented on api/v1/api.proto
> +  string end_date = 2;
message `UsageTime`
```suggestion
UsageTime recorded_time_span = 1;
```

2022-10-26 21:47 UTC, leonardpahlke commented on api/v1/api.proto
> +  string end_date = 2;
message `UsageTime`
```suggestion
UsageTime recorded_time_span = 1;
```

2022-10-26 21:47 UTC, leonardpahlke commented on api/v1/api.proto
> +  string account = 4;
new message `Provider`? (needs to get created)
```suggestion
Provider provider = 3;
```

2022-10-26 21:47 UTC, leonardpahlke commented on api/v1/model/model.proto
> +}
? we already have a message Emission & CarbonRecord why is this needed?
```suggestion
```

2022-10-26 21:47 UTC, leonardpahlke commented on api/v1/api.proto
> +  string region = 5;
```suggestion
Location location = 5;
```

2022-10-26 21:47 UTC, leonardpahlke commented on api/v1/api.proto
> +  string account = 4;
I think we can define a message new message here to abstract `provider` with a list of account ids (maybe more fields?) 
```suggestion
Provider provider = 3;
```
(`Provider` needs to be defined)

2022-10-26 21:47 UTC, leonardpahlke commented on api/v1/api.proto
> +  repeated carbonaut.api.v1.model.Footprint footprints = 1;
maybe reuse `Emissions` ?
```suggestion
repeated carbonaut.api.v1.model.Emission emissions = 1;
```

2022-10-26 21:47 UTC, leonardpahlke commented on api/v1/model/model.proto
> +}
I think we can reuse the `Emission` message at this point.
```suggestion
message ProjectEmission {
  Provider provider = 1;
  repeated Emission emissions = 2;
  // more?
}
```

2022-10-27 16:21 UTC, bcesur commented on api/v1/model/model.proto
> +}
Yeah when I was creating the API spec I thought we would need something like this but converting the stuff to .proto I realized that we have similar stuff already. Added this to have your opinion. Removing it.

2022-10-27 16:49 UTC, leonardpahlke requested changes

2022-10-27 16:49 UTC, leonardpahlke commented on api/v1/model/model.proto
> +    string cloud_provider = 1;
i think we can define an `enum` with a selection `AWS, GCP, KUBERNETES, SELF_HOSTED, ... other clouds ...`

2022-10-27 16:49 UTC, leonardpahlke commented on api/v1/api.proto
> +}
what is a service? ITResource? or smth different?

2022-10-27 16:49 UTC, leonardpahlke commented on api/v1/api.proto
> +message ListServicesForProjectRequest {}
empty?

2022-10-27 16:49 UTC, leonardpahlke commented on api/v1/api.proto
> +message ListAccountsForProjectRequest {}
empty?

2022-10-27 16:49 UTC, leonardpahlke commented on api/v1/api.proto
> +  repeated string accounts = 1;
maybe return `Provider`?

2022-10-27 16:49 UTC, leonardpahlke commented on api/v1/api.proto
> +  rpc ListAccounts (ListAccountsForProjectRequest) returns (ListAccountsForProjectResponse) {}
```suggestion
rpc ListProviderAccounts (ListProviderAccountsRequest) returns (ListProviderAccountsResponse) {}
```

2022-10-27 16:49 UTC, leonardpahlke commented on api/v1/api.proto
> +
```suggestion
rpc ListProviders (ListProvidersRequest) returns (ListProvidersResponse) {}

```
new endpoint to list configured providers?

2022-10-27 22:25 UTC, bcesur commented on api/v1/api.proto
> +}
So the name of the service that generated the emission. For AWS it can be EC2 or for GCP it can be cloud engine. It is actually an ITResource.

2022-10-27 22:28 UTC, bcesur commented on api/v1/api.proto
> +message ListServicesForProjectRequest {}
I was thinking in the REST way here. To parse the user's auth token then get the IAM information. This is why I left it empty. It's the same thing for below

2022-10-27 22:54 UTC, leonardpahlke approved these changes
lgtm from my side

cc @christopherfriedrich @mkorbi

2022-10-28 00:57 UTC, merged